nodeLinker: node-modules

## this cannot be deployed or pipeline will fail
### alternatively we can keep the source files in the repo, so we need to exclude it from .gitignore
yarnPath: .yarn/releases/yarn-3.5.0.cjs
